### PR TITLE
Use proper capitalisation of CC and ODbL licenses

### PR DESCRIPTION
**Pull request by Freso**
See https://creativecommons.org/licenses/by-sa/3.0/ and https://opendatacommons.org/licenses/odbl/ for reference on how the license authors capitalise the license abbreviations.

### CODE REVIEW

**Comment by Freso** [comment]
Should I rebase this on top of `alpha` instead of `master`?

**Comment by wish7code** [comment]
Thx! alpha would be the preferred variant.

But that should be an easy effort: 

According to github the PR author (you) may change the target branch to alpha via GUI (see https://github.com/blog/2224-change-the-base-branch-of-a-pull-request),

PS: I don't understand why the repo owner can't change the target branch via GUI - seems like a pretty common use case..

**Comment by Freso** [comment]
I've changed base now, but I will probably need to `rebase` as well. I'll try and do that later tonight or this weekend.

**Comment by Freso** [comment]
Rebased the branch on top of `alpha`. Should be all good to go now. 👍

**Comment by Freso** [comment]
Ping @wish7code ?

**Comment by wish7code** [comment]
Thanks for the ping :-)

**Pull request merged**
